// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSSNDcmKCUC8z71_ielr6r2wa-_YKGwJk',
    appId: '1:464815866923:web:e01eeea7b3efe1e38b966e',
    messagingSenderId: '464815866923',
    projectId: 'planner-85eca',
    authDomain: 'planner-85eca.firebaseapp.com',
    storageBucket: 'planner-85eca.firebasestorage.app',
    measurementId: 'G-4W3KHLM4MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLiT3_uCC8f1jMz0Y5T5zThEH-ikOeYEg',
    appId: '1:464815866923:android:ca5790fec0bfee1c8b966e',
    messagingSenderId: '464815866923',
    projectId: 'planner-85eca',
    storageBucket: 'planner-85eca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwiP6cBBXzF5_p2hRrjR8Pv0zhdrBsgls',
    appId: '1:464815866923:ios:5a39bf94e82ac4568b966e',
    messagingSenderId: '464815866923',
    projectId: 'planner-85eca',
    storageBucket: 'planner-85eca.firebasestorage.app',
    iosBundleId: 'com.example.planner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwiP6cBBXzF5_p2hRrjR8Pv0zhdrBsgls',
    appId: '1:464815866923:ios:5a39bf94e82ac4568b966e',
    messagingSenderId: '464815866923',
    projectId: 'planner-85eca',
    storageBucket: 'planner-85eca.firebasestorage.app',
    iosBundleId: 'com.example.planner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSSNDcmKCUC8z71_ielr6r2wa-_YKGwJk',
    appId: '1:464815866923:web:2c9181690392967b8b966e',
    messagingSenderId: '464815866923',
    projectId: 'planner-85eca',
    authDomain: 'planner-85eca.firebaseapp.com',
    storageBucket: 'planner-85eca.firebasestorage.app',
    measurementId: 'G-KVV5CQTPHF',
  );
}
